server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mirea-vkr/config-service # ?????? ?? Git-??????????? ? ??????????????
          default-label: main # ????? ???????????
          search-paths: config # ????? ? ????????? ?????? ???????????
          clone-on-start: true # ??????????? ??????????? ??? ?????? ???????

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # ?????? ?? Eureka Server
      register-with-eureka: true # ?????????????? ? Eureka
      fetch-registry: true       # ???????? ?????? ?? Eureka
