server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mirea-vkr/config-service
          default-label: main
          search-paths: config
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
