server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG



spring:
  main:
    allow-circular-references: true
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/v1/movies/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**



