server:
  port: 8080


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/config/**
        - id: eureka-service
          uri: lb://eureka-service
          predicates:
            - Path=/eureka/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:5173"  # или адрес фронтенда
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders: "*"
#            allowCredentials: true



