server:
  port: 8080


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/v1/movies/**



