server:
  port: 8083

spring:
  application:
    name: movie-service

  datasource:
    url: jdbc:postgresql://postgres-movie:5432/movie_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#  cache:
#    type: simple

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/


kinopoisk:
  api:
    key: WKQTT1D-Z9CMG56-HHG0SR5-Y66HA0F

