server:
  port: 8084

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:postgresql://postgres-review:5432/review_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true



eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/




